get:
  tags:
    - returns
    - fbs
    - fby
    - dbs
    - express
  x-auth-scopes:
    - all-methods
    - all-methods:read-only
    - inventory-and-order-processing
    - inventory-and-order-processing:read-only
  operationId: getReturnApplication
  summary: Получение заявления на возврат
  description: >
    {% include notitle
    [:no-translate[access]](../../_auto/method_scopes/getReturnApplication.md)
    %}


    Загружает заявление покупателя на возврат товара.


    |**:no-translate[⚙️] Лимит:** 10 000 запросов в час|

    |-|
  parameters:
    - $ref: ../components/parameters/CampaignId.yaml
    - $ref: ../components/parameters/OrderId.yaml
    - $ref: ../components/parameters/ReturnId.yaml
  responses:
    '200':
      description: Заявление на возврат.
      content:
        application/octet-stream:
          schema:
            type: string
            format: binary
    '400':
      $ref: ../components/responses/400.yaml
    '401':
      $ref: ../components/responses/401.yaml
    '403':
      $ref: ../components/responses/403.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '420':
      $ref: ../components/responses/420.yaml
    '500':
      $ref: ../components/responses/500.yaml
