description: Настройки магазина.
type: object
required:
  - taxation
properties:
  countryRegion:
    description: Идентификатор региона, в котором находится магазин.
    type: integer
    format: int64
  shopName:
    description: |
      Наименование магазина на Яндекс Маркете.
      Если наименование отсутствует, значение параметра выводится — `null`.
    type: string
  showInContext:
    description: "{% note warning \"Параметр устарел и будет отключен 12.10.2026.\" %}\n\n\_\n\n{% endnote %}\n\nПризнак размещения магазина на сайтах партнеров Яндекс Дистрибуции.\nВозможные значения:\n* `false` — магазин не размещен на сайтах партнеров Яндекс Дистрибуции.\n* `true` — магазин размещен на сайтах партнеров Яндекс Дистрибуции.\n"
    type: boolean
    deprecated: true
    x-deprecation-config:
      shutdown-date: '2026-10-12'
  showInPremium:
    description: "{% note warning \"Параметр устарел и будет отключен 12.10.2026.\" %}\n\n\_\n\n{% endnote %}\n\nПризнак показа предложений магазина в блоке над результатами поиска (cпецразмещение).\nВозможные значения:\n* `false` — предложения не показываются в блоке cпецразмещения.\n* `true` — предложения показываются в блоке cпецразмещения.\n"
    type: boolean
    deprecated: true
    x-deprecation-config:
      shutdown-date: '2026-10-12'
  useOpenStat:
    description: "{% note warning \"Параметр устарел и будет отключен 12.10.2026.\" %}\n\n\_\n\n{% endnote %}\n\nПризнак использования внешней интернет-статистики.\nВозможные значения:\n* `false` — внешняя интернет-статистика не используется.\n* `true` — внешняя интернет-статистика используется.\n"
    type: boolean
    deprecated: true
    x-deprecation-config:
      shutdown-date: '2026-10-12'
  localRegion:
    $ref: ./CampaignSettingsLocalRegionDTO.yaml
  taxation:
    $ref: ./TaxationInfoDTO.yaml
