description: |
  Источник информации о расписании работы службы доставки.
  Возможные значения:
  * `WEB` — информация получена из настроек кабинета продавца на Маркете.
  * `YML` — информация получена из прайс-листа магазина.
type: string
enum:
  - WEB
  - YML
