description: >
  Источник информации о расписании работы службы доставки.

  Возможные значения:

  * :no-translate[`WEB`] — информация получена из настроек кабинета продавца на
  Маркете.

  * :no-translate[`YML`] — информация получена из прайс-листа магазина.
type: string
enum:
  - WEB
  - YML
